 import g4p_controls.*;
GTextArea textarea1;  
public void textarea1_change1(GTextArea source, GEvent event) { //_CODE_:textarea1:638800:
  getInput().text=textarea1.getText();
  
} 

// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  textarea1 = new GTextArea(this, 200, 200, 148, 104, G4P.SCROLLBARS_NONE);
  textarea1.setOpaque(true);
  textarea1.addEventHandler(this, "textarea1_change1");
  
}
